env:
  global:
    - TERM=dumb
dist: trusty
notifications:
  email: false
git:
  quiet: true
  depth: 1
language: java
jdk: openjdk8
node_js: lts/*
python: 3
services:
  - docker
addons:
  apt:
    update: true
    packages:
      - jq
      - bash
      - sudo
      - lsof
      - wget
      - curl
      - unzip
      - python3-pip
      - docker-ce
install: true
before_install:
  - export PATH=$HOME/.local/bin:$PATH
  - pip3 install --user $(whoami) --upgrade pip
  - pip install --user $(whoami) --upgrade httpie
  - http --version --debug
  - docker-compose version
jobs:
  include:
    - stage: test
      jdk: openjdk8
      name: tests
      script: cd $TRAVIS_BUILD_DIR && ./gradlew clean test dependencyUpdates -Drevision=release
#      script:
#        - cd $TRAVIS_BUILD_DIR
#        - ./gradlew clean test
#        - ./gradlew dependencyUpdates -Drevision=release
cache:
  directories:
    - ~/.gradle
  packages: true
  pip: true
