env:
  global:
    - TERM=dumb
dist: trusty
notifications:
  email: false
git:
  quiet: true
  depth: 1
language: java
jdk: openjdk8
node_js: lts/*
python: 3
services:
  - docker
addons:
  apt:
    update: true
    packages:
      - jq
      - bash
      - sudo
      - lsof
      - wget
      - curl
      - unzip
      - python3-pip
      - docker-ce
install: true
before_install:
  - export PATH=$HOME/.local/bin:$PATH
  - pip3 install --user $(whoami) --upgrade pip
  - pip install --user $(whoami) --upgrade httpie
  - http --version --debug
  - docker-compose version
  #
  - source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
  - stop_any 9092 2181 80 8001 8002 8080 5432
jobs:
  include:
    - stage: test
      jdk: openjdk8
      name: tests
      script: cd $TRAVIS_BUILD_DIR && ./gradlew clean test dependencyUpdates -Drevision=release
    - stage: test
      jdk: openjdk8
      name: integration tests
      script:
        - cd $TRAVIS_BUILD_DIR && ./gradlew
        - java -jar $TRAVIS_BUILD_DIR/build/libs/*-SNAPSHOT.jar &
        - wait_for 8080
        #
        - http :8080/user/load id=00000000-0000-0000-0000-000000000000
        #
        - http :8080/user-account/create id=00000000-0000-0000-0000-000000000000 username=bob
        - http :8080/user-account/close id=00000000-0000-0000-0000-000000000000 reason=hz
        - http :8080/user-account/reactivate id=00000000-0000-0000-0000-000000000000
        #
        - http :8080/user-account/create id=11111111-1111-1111-1111-111111111111 username=max
        - http :8080/friend-request/send
            fromUserId=00000000-0000-0000-0000-000000000000
            toUserId=11111111-1111-1111-1111-111111111111
            greeting='Hey!' || echo 'oops... implement me please!'
        #
        - http post :8080/http-server/shutdown
        #
        - stop_any 80 8080
cache:
  directories:
    - ~/.gradle
  packages: true
  pip: true
