# Read more: https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html

# curl localhost:8080/user/create -H"content-type: application/json"
GET localhost:8080/
Content-Type: application/json
Accept: application/json

###
# curl localhost:8080/user/recreate -d'{"username": "bob", "id": "00000000-0000-0000-0000-000000000000"}' -H"content-type: application/json"
POST localhost:8080/user/create
Content-Type: application/json
Accept: application/json

{
  "id": "00000000-0000-0000-0000-000000000000",
  "username": "bob"
}

###
# curl localhost:8080/user/suspend -d'{"id": "00000000-0000-0000-0000-000000000000"}' -H"content-type: application/json"
POST localhost:8080/user/suspend
Content-Type: application/json
Accept: application/json

{
  "id": "00000000-0000-0000-0000-000000000000"
}

###
# curl localhost:8080/user/recreate -d'{"id": "00000000-0000-0000-0000-000000000000"}' -H"content-type: application/json"
POST localhost:8080/user/recreate
Content-Type: application/json
Accept: application/json

{
  "id": "00000000-0000-0000-0000-000000000000"
}

###
# curl localhost:8080/user/reactivate -d'{"id": "00000000-0000-0000-0000-000000000000"}' -H"content-type: application/json"
POST localhost:8080/user/reactivate
Content-Type: application/json
Accept: application/json

{
  "id": "00000000-0000-0000-0000-000000000000"
}

###
POST localhost:8080/server/shutdown
Content-Type: application/json
Accept: application/json

###
